### ISSUE TITLE
Google Maps: Cant add styles to options

### ISSUE THREAD

**Issue by MickL** [nuxt/scripts#202]
### 🐛 The bug

When adding `styles` to prop `options` of `<ScriptGoogleMaps :options="{}" />` they dont get applied. Instead a warning is shown in the console:

> Google Maps JavaScript API: A Map's styles property cannot be set when a mapId is present. When a mapId is present, Map styles are controlled via the cloud console.

I did not set any mapId.

**Comment by harlan-zw** [comment]
Thanks for the issue, this should be fixed in the latest version. Providing `mapOptions.styles` will style the static map and the interactive map.

![image](https://github.com/user-attachments/assets/ffa194e9-1d1e-4944-aa52-15b9312288aa)

![image](https://github.com/user-attachments/assets/c8eda7ef-7c1c-4421-b18c-d96427adca53)
