### ISSUE TITLE
Unable to read property of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by olliescase** [nuxt/scripts#240]
### 🐛 The bug

When upgrading the package from:
v0.7.1 -> v0.8.0

We encountered the following issue:

Error in the console:

`[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'startsWith')`

From source:

```js
 ss(n.vueApp.config.globalProperties, "$nuxt", n);
    {
        window.addEventListener("nuxt.preloadError", s => {
            n.callHook("app:chunkError", {
                error: s.payload
            })
        }
        ),
        window.useNuxtApp = window.useNuxtApp || le;
        const i = n.hook("app:error", (...s) => {
            console.error("[nuxt] error caught during app initialization", ...s)
        }
        );
        n.hook("app:mounted", i)
    }
    const r = n.payload.config;
    return n.provide("config", r),
    n
}
```

### 🛠️ To reproduce

/

### 🌈 Expected behavior

No error

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. It's not exactly clear where the issue is from, ideally a reproduction would be provided so I could verify.

However, I have pushed up a fix for a _possible_ issue where a script is registered without a src.

If you still have issues with 0.8.1 please provide a reproduction :pray:
