### ISSUE TITLE
Option to disable script preloading

### ISSUE THREAD

**Issue by ykunimoto** [nuxt/scripts#280]
### 🆒 Your use case

When using [Nuxt Security](https://nuxt-security.vercel.app/) to set CSP headers for universal rendering, the scripts loaded via `useScript` work as expected, but the preloading of scripts using `link` tags does not work and generates errors.

### 🆕 The solution you'd like

It would be ideal if there was a way to disable script preloading through the `ScriptOptions`.

**Comment by vejja** [comment]
Hi @ykunimoto 

Nuxt Security here.
Would you mind sending a screenshot of:
- the HTML response where we can see the faulty `<link>` tags 
- your `nuxt.config.ts`

Thanks

**Comment by ykunimoto** [comment]
Hi @vejja 

First, I’d like to apologize for the confusion. It turns out that the pages where the preloading error occurs are pre-rendered, while other routes in my project use different rendering modes.

I’ve created a minimal reproduction: https://stackblitz.com/edit/nuxt-starter-vorysp

<img width="673" alt="image" src="https://github.com/user-attachments/assets/28d298b8-e3ce-4bdc-8c42-ce83ce8e1e0d">
<img width="978" alt="image" src="https://github.com/user-attachments/assets/5dd3c6c4-39ea-4f6a-a171-7156f5e9d304">

**Comment by vejja** [comment]
Because your pages are prerendered as static assets, you need to load the script in client mode:

```ts
export default defineNuxtConfig({
  scripts: {
    registry: {
      googleTagManager: {
        id: 'GTM-XXXXX',
        scriptOptions: { trigger: 'client' },
      },
    },
  },
});
```

@harlan-zw shouldn't it be the default by the way? I think I remember `useScript` defaults to `'client'`, but this might have changed with the registry

**Comment by ykunimoto** [comment]
Enabling client mode solved the issue. Thank you for the support!

**Comment by harlan-zw** [comment]
@vejja We now add a preload / preconnect for the script src when SSRing a page that uses `useScript`. This ensures the script will load as quickly as possible when Nuxt is finished hydrating.

Can Nuxt Security support this?

**Comment by vejja** [comment]
We do support this, but I think the issue is that `onNuxtReady` triggers during static pre-rendering at build time. 

Let me clarify the sequence of **build-time** events as I understand them (maybe wrong of course)

| User wants | static | universal |
|---|---|---|
| nuxi | generate | build |
| trigger | _onNuxtReady_ | onNuxtReady |
| NuxtScripts | inserts preload | inserts preload |
| NuxtSecurity | _cannot insert hash*_ | inserts nonce |
| HTML code | has nothing | has nonce | 
| CSP applies | _hash miss_ | nonce |
| CSP result | denial | pass |

*This only happens in `generate` mode, where CSP is governed by hash. In `build` mode, CSP is governed by nonce so we don't have an issue.

Now if I draw the same table with `{ trigger: 'client' }` it becomes:

| User wants | static | universal |
|---|---|---|
| nuxi | generate | build |
| trigger | _client_ | client |
| NuxtScripts | nothing | nothing |
| NuxtSecurity | nothing | nothing |
| HTML code | nothing | nothing |
| CSP applies | _strict-dynamic_ | strict-dynamic |
| CSP result | pass | pass |

**Comment by Oui-Dev** [comment]
I have the exact same issue using Matomo scripts and SSG. I already try to add `scriptOptions: { trigger: 'client' },` but it won't work, I think it's a google option not avalaible for Matomo 🥲
